# Generated by Django 4.1.3 on 2022-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='expired',
        ),
        migrations.AlterField(
            model_name='tour',
            name='target',
            field=models.IntegerField(),
        ),
    ]
